// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogchuoeodgoprzqptsjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nY2h1b2VvZGdvcHJ6cXB0c2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjc5NTYsImV4cCI6MjA2NDY0Mzk1Nn0._HPSUfD7ijGPMNFCLbSwOuBI2_xtUAbYtBGp6IoI4Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);